# .github/workflows/pachca-retro.yml
name: Pachca Retro (biweekly Mon 14:00 MSK)

on:
  schedule:
    # 14:00 МСК = 11:00 UTC
    - cron: '0 8 * * 1'
  workflow_dispatch: {}

jobs:
  retro:
    runs-on: ubuntu-latest
    env:
      WEBHOOK_URL: ${{ secrets.PACHCA_WEBHOOK_URL }}  # положи вебхук Пачки в Secrets
      ANCHOR_MONDAY: '2025-09-01'                     # понедельник первой ретро-недели

    steps:
      - name: Check secret
        shell: bash
        run: '[ -n "$WEBHOOK_URL" ] || { echo "PACHCA_WEBHOOK_URL not set"; exit 1; }'

      - name: Plan (decide and prepare body.json)
        id: plan
        shell: bash
        run: >-
          SHOULD=$(python3 -c "import os; from datetime import datetime,timedelta,date,timezone;
          now=datetime.now(timezone.utc); msk=now+timedelta(hours=3);
          monday=(msk.date()-timedelta(days=msk.weekday()));
          anchor=date.fromisoformat(os.environ['ANCHOR_MONDAY']);
          weeks=(monday-anchor).days//7;
          print(1 if (weeks>=0 and weeks%2==0) else 0)");
          echo "should_send=$SHOULD" >> "$GITHUB_OUTPUT";
          if [ "$SHOULD" = "1" ]; then
            BODY=$(python3 -c "import json; print(json.dumps({'message':'@ReleaseTeam Сегодня ретро в 16:00 ЕКБ, пришло время повспоминать чем хотелось бы поделиться, ссылка на доску: https://unidraw.io/app/board/25be0ac5c3cebcef471a?elementId=ah6ZCbHO8vzu_qrMQSC5- Ссылка на подключение: https://ideco.ktalk.ru/releaseteam'}, ensure_ascii=False))");
            printf '%s' "$BODY" > body.json;
          fi

      - name: Send (only on retro week)
        if: steps.plan.outputs.should_send == '1'
        shell: bash
        run: >-
          curl --fail --show-error --silent
          -H "Content-Type: application/json"
          -X POST "$WEBHOOK_URL"
          --data-binary @body.json

      - name: Skip (non-retro week)
        if: steps.plan.outputs.should_send != '1'
        run: 'echo "Skip: not a retro week."'
