name: Pachca Standup Reminder

on:
  schedule:
    # 11:00 МСК = 08:00 UTC
    - cron: '55 6 * * 1-5'
  workflow_dispatch:
    inputs:
      message:
        description: 'Текст сообщения'
        required: false
        default: 'Встречаемся на дейли через 5 минут!'

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка секрета
        run: |
          if [ -z "${{ secrets.PACHCA_WEBHOOK_URL }}" ]; then
            echo "Secret PACHCA_WEBHOOK_URL не задан"; exit 1
          fi

      - name: Отправить уведомление в Пачку
        env:
          WEBHOOK_URL: ${{ secrets.PACHCA_WEBHOOK_URL }}
          MESSAGE: "${{ github.event.inputs.message }}"
        run: |
          # Если запустили по расписанию, MESSAGE будет пустая — зададим дефолт.
          : "${MESSAGE:= Встречаемся на дейли через 5 минут!}"
          # Собираем JSON одной командой Python (без heredoc и jq)
          BODY=$(python3 -c 'import json,os; print(json.dumps({"message": os.environ["MESSAGE"]}, ensure_ascii=False))')
          curl --fail --show-error --silent \
               -H "Content-Type: application/json" \
               -X POST "$WEBHOOK_URL" \
               -d "$BODY"
