# .github/workflows/pachca-retro.yml
name: Pachca Retro (biweekly Mon 14:00 MSK)

on:
  schedule:
    # 14:00 МСК = 11:00 UTC
    - cron: '0 8 * * 1'
  workflow_dispatch: {}

jobs:
  retro:
    runs-on: ubuntu-latest
    env:
      WEBHOOK_URL: ${{ secrets.PACHCA_WEBHOOK_URL }}  # входящий вебхук Пачки
      ANCHOR_MONDAY: '2025-09-01'                    # понедельник первой ретро-недели

    steps:
      - name: Проверка секрета
        run: |
          if [ -z "$WEBHOOK_URL" ]; then
            echo "PACHCA_WEBHOOK_URL не задан"; exit 1;
          fi

      - name: Решить, ретро-неделя ли сейчас, и при необходимости собрать body.json
        id: plan
        run: |
          # 1) Решаем, наша ли неделя (чётность от ANCHOR_MONDAY)
          SHOULD=$(python3 -c "import os,sys; from datetime import datetime,timedelta,date,timezone; \
AM=os.environ['ANCHOR_MONDAY']; now=datetime.now(timezone.utc); msk=now+timedelta(hours=3); \
monday=(msk.date()-timedelta(days=msk.weekday())); anchor=date.fromisoformat(AM); \
weeks=(monday-anchor).days//7; print(1 if (weeks>=0 and weeks%2==0) else 0)")
          echo "should_send=${SHOULD}" >> "$GITHUB_OUTPUT"

          # 2) Если ретро-неделя — готовим JSON для отправки
          if [ "$SHOULD" = "1" ]; then
            python3 -c "import json; \
msg='@ReleaseTeam Сегодня ретро в 16:00 ЕКБ, пришло время повспоминать чем хотелось бы поделиться, ссылка на доску: https://unidraw.io/app/board/25be0ac5c3cebcef471a?elementId=ah6ZCbHO8vzu_qrMQSC5- Ссылка на подключение: https://ideco.ktalk.ru/releaseteam'; \
open('body.json','w',encoding='utf-8').write(json.dumps({'message': msg}, ensure_ascii=False))"
          else
            echo "Not a retro week, skip."
          fi

      - name: Отправить сообщение в Пачку (только на ретро-неделе)
        if: steps.plan.outputs.should_send == '1'
        run: |
          curl --fail --show-error --silent \
            -H "Content-Type: application/json" \
            -X POST "$WEBHOOK_URL" \
            --data-binary @body.json

      - name: Пропуск (не ретро-неделя)
        if: steps.plan.outputs.should_send != '1'
        run: echo "Skip: not a retro week."
